name: Publish

run-name: ${{ github.actor }} publishing project ☁

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    env:
      DOTNET_TFM: net10.0
    outputs:
      DOTNET_VERSION: ${{ steps.setup_dotnet.outputs.dotnet-version }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: setup dotnet
        id: setup_dotnet
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: ${{ github.workspace }}/global.json

      - name: dotnet restore
        id: dotnet_restore
        run: dotnet restore

      - name: dotnet build
        id: dotnet_build
        run: dotnet build --no-restore -c Release

      - name: dotnet test
        id: dotnet_test
        run: |
          dotnet run --no-build -c Release --project ${{ github.workspace }}/test/Net.Belt.Tests/ -- \
            --coverage \
            --settings test/.runsettings \
            --config-file test/testconfig.json

      - name: dotnet pack
        id: dotnet_pack
        run: dotnet pack --no-build -c Release ${{ github.workspace }}/src/Net.Belt/

      - name: report test results
        id: report_test_results
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: Test Report
          path: ${{ github.workspace }}/test/Net.Belt.Tests/bin/Release/*/TestResults/*.Tests.xml
          reporter: dotnet-nunit
          fail-on-error: true

      - name: report coverage
        if: ${{ !env.ACT }}
        uses: leoriviera/CodeCoverageSummary-arm64@v1.3.1
        with:
          filename: ./test/Net.Belt.Tests/bin/Release/${{ env.DOTNET_TFM }}/TestResults/Net.Belt.cobertura.xml
          badge: true
          fail_below_min: false
          format: markdown
          output: both
          indicators: true
          thresholds: "30 70"

      - name: report local coverage
        if: ${{ env.ACT }}
        uses: leoriviera/CodeCoverageSummary-arm64@v1.3.1
        with:
          filename: ./test/Net.Belt.Tests/bin/Release/${{ env.DOTNET_TFM }}/TestResults/Net.Belt.cobertura.xml
          badge: true
          fail_below_min: false
          format: markdown
          output: both
          indicators: true
          thresholds: "30 70"

      - name: upload coverage
        uses: codecov/codecov-action@v5.5.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          dry_run: ${{ env.ACT }}
          fail_ci_if_error: false
          files: ${{ github.workspace }}/test/Net.Belt.Tests/bin/Release/${{ env.DOTNET_TFM }}/TestResults/Net.Belt.cobertura.xml
          slug: dgg/net-belt

      - name: copy coverage report to ResultDirectory
        run: cp ${{ github.workspace }}/code-coverage-results.md ${{ github.workspace }}/test/Net.Belt.Tests/bin/Release/${{ env.DOTNET_TFM }}/TestResults/Net.Belt.coverage.md

      - name: upload test results
        id: upload_test_results
        uses: actions/upload-artifact@v5
        with:
          name: test-results
          path: ${{ github.workspace }}/test/Net.Belt.Tests/bin/Release/${{ env.DOTNET_TFM }}/TestResults/

      - name: upload bin
        id: upload_bin
        uses: actions/upload-artifact@v5
        with:
          name: bin
          path: |
            ${{ github.workspace }}/src/Net.Belt/bin/Release/${{ env.DOTNET_TFM }}/*.dll
            ${{ github.workspace }}/src/Net.Belt/bin/Release/${{ env.DOTNET_TFM }}/*.pbd
            ${{ github.workspace }}/src/Net.Belt/bin/Release/${{ env.DOTNET_TFM }}/*.xml

      - name: upload package
        id: upload_package
        uses: actions/upload-artifact@v5
        with:
          name: package
          path: ${{ github.workspace }}/src/Net.Belt/bin/Release/*.nupkg

      - run: echo "☑ status is ${{ job.status }}"

  push_nuget_package:
    needs: build_and_publish
    runs-on: ubuntu-latest
    environment: "Nuget Feed"
    steps:
      - name: download package
        uses: actions/download-artifact@v6
        with:
          name: package

      - name: setup dotnet for pushing
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{needs.build_and_publish.outputs.DOTNET_VERSION}}

      - name: push to nuget feed
        id: push_to_nuget_feed
        run: dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_KEY }} --source nuget.org
