name: Validate

run-name: ${{ github.actor }} validating project ✔

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      DOTNET_TFM: net10.0
    steps:
      - name: Check out repository code
        id: checkout
        uses: actions/checkout@v5

      - name: setup dotnet
        id: setup_dotnet
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: ${{ github.workspace }}/global.json

      - name: dotnet restore
        id: dotnet_restore
        run: dotnet restore

      - name: dotnet build
        id: dotnet_build
        run: dotnet build --no-restore -c Release

      - name: dotnet test
        id: dotnet_test
        run: |
          dotnet run --no-build -c Release --project ${{ github.workspace }}/test/Net.Belt.Tests/ -- \
          --coverage \
          --settings ${{ github.workspace }}/test/.runsettings \
          --config-file ${{ github.workspace }}/test/testconfig.json
  
      - name: report tests
        id: report_tests
        uses: dorny/test-reporter@v2
        with:
          name: Test Report
          path: ${{ github.workspace }}/test/Net.Belt.Tests/bin/Release/*/TestResults/*.Tests.xml
          reporter: dotnet-nunit
          fail-on-error: true

      - name: report local coverage
        id: report_local_coverage
        if: ${{ env.ACT }}
        uses: leoriviera/CodeCoverageSummary-arm64@v1.3.1
        with:
          filename: ./test/Net.Belt.Tests/bin/Release/${{ env.DOTNET_TFM }}/TestResults/Net.Belt.cobertura.xml
          badge: true
          fail_below_min: false
          format: markdown
          output: both
          indicators: true
          thresholds: "30 70"

      - name: report coverage
        id: report_coverage
        if: ${{ !env.ACT }}
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: ./test/Net.Belt.Tests/bin/Release/${{ env.DOTNET_TFM }}/TestResults/Net.Belt.cobertura.xml
          badge: true
          fail_below_min: false
          format: markdown
          output: both
          indicators: true
          thresholds: "30 70"

      - name: comment coverage
        id: comment_coverage
        uses: marocchino/sticky-pull-request-comment@v2.9.4
        with:
          recreate: true
          path: ${{ github.workspace }}/code-coverage-results.md

      - run: echo "☑ status is ${{ job.status }}"