name: Validate

run-name: ${{ github.actor }} validating project ✔

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: setup dotnet
        id: setup_dotnet
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: ./global.json

      - name: dotnet restore
        id: dotnet_restore
        run: dotnet restore

      - name: dotnet build
        id: dotnet_build
        run: dotnet build --no-restore -c Release

      - name: dotnet test
        id: dotnet_test
        run: dotnet run --no-build -c Release --project test/Net.Belt.Tests/ -- --settings test/.runsettings

      - name: report tests
        id: report_tests
        uses: dorny/test-reporter@v2
        with:
          name: Test Report
          path: ./test/Net.Belt.Tests/bin/Release/*/TestResults/*.Tests.xml
          reporter: dotnet-nunit
          fail-on-error: true

      - run: echo "☑ status is ${{ job.status }}"